server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
  datasource:
    password: 123
    url: jdbc:postgresql://localhost:5432/postgres
    username: test
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true